"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import AppShell from "../app-shell";
import { api } from "../../lib/api";
type P={display_name?:string;date_of_birth?:string;gender?:string;marital_status?:string;location?:string;education?:string;profession?:string;bio?:string;interests?:string[];lifestyle?:string[];values?:string[];profile_complete_pct?:number};

export default function Profile(){const[p,setP]=useState<P>({});useEffect(()=>{api<P>("/api/v1/profiles/me").then(setP).catch(()=>undefined)},[]);
return <AppShell><main className="mx-auto max-w-6xl px-5 py-8 md:px-10 md:py-12"><div className="grid gap-6 md:grid-cols-[310px_1fr]">
<aside className="rounded-[32px] bg-[#231f20] p-7 text-white shadow-[0_25px_70px_rgba(55,34,30,.15)]"><div className="mx-auto flex h-44 w-44 items-center justify-center rounded-full border border-white/20 bg-[radial-gradient(circle_at_65%_30%,#e8c7bb,#a6535e_55%,#6c3942)] text-6xl">{p.display_name?.[0]||"M"}</div><h1 className="mt-6 text-center text-3xl">{p.display_name||"Your profile"}</h1><p className="mt-1 text-center font-sans text-xs text-white/50">mangalamm · මංගලම්</p><div className="mt-7 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#e8b2ad]" style={{width:`${p.profile_complete_pct||0}%`}}/></div><p className="mt-2 text-center font-sans text-xs text-white/50">{p.profile_complete_pct||0}% complete</p><Link href="/onboarding" className="mt-6 block rounded-full bg-white py-3 text-center font-sans text-xs font-semibold text-[#231f20]">Edit profile</Link></aside>
<section className="space-y-5"><div className="rounded-[32px] border border-[var(--line)] bg-white p-7 shadow-soft md:p-9"><p className="font-sans text-[10px] font-semibold uppercase tracking-[.23em] text-[var(--rose)]">About you</p><h2 className="mt-3 text-4xl tracking-[-.03em]">The person behind the profile.</h2><div className="mt-7 grid gap-3 sm:grid-cols-2">{[["Location",p.location],["Education",p.education],["Profession",p.profession],["Marital status",p.marital_status],["Gender",p.gender]].map(([label,value])=><div key={String(label)} className="rounded-2xl bg-[var(--paper)] p-4"><span className="font-sans text-[10px] uppercase tracking-[.12em] text-[var(--muted)]">{label}</span><p className="mt-1 text-sm">{value||"Not added yet"}</p></div>)}</div>{p.bio&&<p className="mt-6 font-sans text-sm leading-7 text-[var(--muted)]">{p.bio}</p>}</div>
<div className="rounded-[32px] border border-[#dbc8bd] bg-[var(--cream)] p-7 md:p-9"><p className="font-sans text-[10px] font-semibold uppercase tracking-[.23em] text-[var(--rose)]">Your signals</p><div className="mt-6 grid gap-6 sm:grid-cols-3">{[["Interests",p.interests],["Lifestyle",p.lifestyle],["Values",p.values]].map(([label,items])=><div key={String(label)}><p className="font-sans text-xs text-[var(--muted)]">{label}</p><p className="mt-2 text-sm leading-6">{Array.isArray(items)&&items.length?items.join(" · "):"Not added yet"}</p></div>)}</div></div></section></div></main></AppShell>}